### ISSUE TITLE
Icons are missing in the AppImage

### ISSUE THREAD

**Issue by probonopd** [jmuelbert/jmbde-QT#11]
jmbde-0.4.7-x86_64.AppImage on Xubuntu 18.04:

![missing](https://user-images.githubusercontent.com/2480569/70379748-4aa5fd80-1928-11ea-8adc-2098b40546fa.png)

Please make sure that the icons are bundled inside the AppImage and are loaded from a path relative to the main application, e.g., a path constructed using  `QCoreApplication::applicationDirPath()`.

**Comment by jmuelbert** [comment]
#11 Closing, add Icons.
